name: "Build"
on:
  pull_request:
  push:
jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: wires
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#stable
  nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: wires
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nightly
