name: "Test Build & Templates"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [stable, nightly]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: wires
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#${{ matrix.package }}

  nightly-template:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        package: [stable, nightly]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          trusted-public-keys = wires.cachix.org-1:7XQoG91Bh+Aj01mAJi77Ui5AYyM1uEyV0h1wOomqjpk= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://wires.cachix.org https://cache.nixos.org/
    - name: Build
      working-directory: ./templates/${{ matrix.package }}
      run: nix build .#neovim --override-input tolerable ../../.
