name: "Test Templates"
on:
  pull_request:
  push:
jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build
      working-directory: ./templates/nightly
      run: nix build .#neovim --override-input tolerable ../../.
  stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build
      working-directory: ./templates/stable
      run: nix build .#neovim --override-input tolerable ../../.

